Protophile/Models/ProtofolioItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Protophile.Models
{
    public class ProtofolioItem
    {
        public int Id { get; set; }
        public string ProtofolioName { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public object Entity { get; internal set; }
    }
}

Protophile/Controllers/ProtofolioItemsController.cs
using Protophile.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Protophile.Controllers
{
    public class ProtofolioItemsController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: ProtofolioItems
        public ActionResult Index()
        {

            return View(db.ProtofolioItems.ToList());
        }

        // GET: ProtofolioItems/Details/5
        public ActionResult Details(int id)
        {
            return View(db.ProtofolioItems.Find(id));
        }

        // GET: ProtofolioItems/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProtofolioItems/Create
        [HttpPost]
        public ActionResult Create(ProtofolioItem protofolioItem , HttpPostedFileBase Upload)
        {

            string path = Path.Combine(Server.MapPath("~/Uploads"), Upload.FileName);
            Upload.SaveAs(path);
            protofolioItem.Image = Upload.FileName;
            db.ProtofolioItems.Add(protofolioItem);
            db.SaveChanges();

          return RedirectToAction("Index");
            
         
        }

        // GET: ProtofolioItems/Edit/5
        public ActionResult Edit(int id)
        {
            return View(db.ProtofolioItems.Find(id));
        }

        // POST: ProtofolioItems/Edit/5
        [HttpPost]
        public ActionResult Edit(ProtofolioItem protofolioItemVM, HttpPostedFileBase Upload)
        {
            // TODO: Add update logic here

            ProtofolioItem protofolioItem = db.ProtofolioItems.Find(protofolioItemVM.Id);
            protofolioItem.ProtofolioName = protofolioItemVM.ProtofolioName;
            protofolioItem.Description = protofolioItemVM.Description;
            if (Upload != null)
            {
                if (!string.IsNullOrEmpty(Upload.FileName))
                {
                    protofolioItem.Image = Upload.FileName;
                    string path = Path.Combine(Server.MapPath("~/Uploads"), Upload.FileName);
                    Upload.SaveAs(path);
                }
            }
            db.Entry(protofolioItem).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
       
        }

        // GET: ProtofolioItems/Delete/5
        public ActionResult Delete(int id)
        {
            return View(db.ProtofolioItems.Find(id));
        }

        // POST: ProtofolioItems/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {

            // TODO: Add delete logic here
            ProtofolioItem protofolioItem = db.ProtofolioItems.Find(id);
            db.ProtofolioItems.Remove(protofolioItem);
            db.SaveChanges();

                return RedirectToAction("Index");
          
        }
    }
}

Protophile/Views/ProtofolioItems/Create.cshtml
@model Protophile.Models.ProtofolioItem

@{
    ViewBag.Title = "Create";
}
<div class="container mb-3" style="margin-top: 8em;">

    <h2>Create</h2>


    @using (Html.BeginForm("Create", "ProtofolioItems", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
<div class="row">
    <div class="col-md-4">
        <div class="form-horizontal">
            <h4>ProtofolioItem</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.ProtofolioName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ProtofolioName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ProtofolioName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </div>

    <div class="form-group  col-md-6 " style="margin-left:40px ;margin-top:80px">
        @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="Upload" onchange="readURL(this);" />
            <img id="blah" src="~/Uploads/defualt.png" alt="your image" style="width:150px;height:150px" />
        </div>
    </div>

  
</div>
    }

    <div style="margin-left:-14px">
        @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-outline-dark", })
    </div>

</div>

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#blah')
                    .attr('src', e.target.result);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

Protophile/Views/ProtofolioItems/Delete.cshtml
@model Protophile.Models.ProtofolioItem

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProtofolioItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProtofolioName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProtofolioName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            <img id="blah" src="~/Uploads/@(Model.Image!=null?Model.Image:"defualt.png")"
                 alt="your image" style="width:150px;height:150px" />
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Protophile/Views/ProtofolioItems/Details.cshtml
@model Protophile.Models.ProtofolioItem

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ProtofolioItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProtofolioName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProtofolioName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            <img id="blah" src="~/Uploads/@(Model.Image!=null?Model.Image:"defualt.png")"
                 alt="your image" style="width:150px;height:150px" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Protophile/Views/ProtofolioItems/Edit.cshtml
@model Protophile.Models.ProtofolioItem

@{
    ViewBag.Title = "Edit";
}
<div class="container mb-3" style="margin-top: 8em;">


    <h2>Edit</h2>


    @using (Html.BeginForm("Edit", "ProtofolioItems", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="row">
            <div class="col-md-6">

                <div class="form-horizontal">
                    <h4>ProtofolioItem</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group">
                        @Html.LabelFor(model => model.ProtofolioName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ProtofolioName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ProtofolioName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="file" name="Upload" onchange="readURL(this);" />
                            <img id="blah" src="~/Uploads/@(Model.Image!=null?Model.Image:"defualt.png")"
                                 alt="your image" style="width:150px;height:150px" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }

    <div style="margin-left:-14px">
        @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-outline-dark" })
    </div>
</div>

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#blah')
                    .attr('src', e.target.result);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

Protophile/Views/ProtofolioItems/Index.cshtml
@model IEnumerable<Protophile.Models.ProtofolioItem>

@{
    ViewBag.Title = "Index";
}

    <h2 style="margin-left: 145px;">protofolio Item</h2>

<link href="~/Content/freelancer.css" rel="stylesheet" />
<p style="margin-left: 145px;">
    @Html.ActionLink("Create New", "Create",null ,new { @class = "btn btn-success" })
</p>
<div class="card-deck" style="margin-left: 130px; margin-right: 130px">
    @foreach (var item in Model)
    {
        <div class="col-md-4 mb-3" @*style="width: 400px"*@>
            <div class="card">
                <img class="card-img-top" src="~/Uploads/@item.Image" @*style="min-height:440px"*@ alt="Card image">
                <div class="card-body" style="padding: 0;">
                    <h4 class="card-title" style="padding:10px;padding-top:15PX">@item.ProtofolioName</h4>
                    <p class="card-text" style="padding-left:10px">@item.Description</p>
                    <div class="card-footer">
                        <a asp-action="Edit" href="https://localhost:44331/ProtofolioItems/Edit/@item.Id" class="btn btn-primary" asp-route-Id="@item.Id"><span class="fa fa-edit"></span> Edit</a>
                        <a asp-action="Details" href="https://localhost:44331/ProtofolioItems/Details/@item.Id" asp-route-Id="@item.Id" class="btn btn-secondary"><span class="fa fa-eye"> View</span></a>
                        <a asp-action="Delete" href="https://localhost:44331/ProtofolioItems/Delete/@item.Id" asp-route-Id="@item.Id" class="btn btn-danger"><span class="fa fa-trash"></span> Delete</a>


                    </div>
                </div>
            </div>
        </div>


    }

</div>